-- USERS
CREATE TABLE IF NOT EXISTS users (
                                     id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     nome  VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cpf   VARCHAR(11)  NOT NULL UNIQUE
    );

-- TRILHAS
CREATE TABLE IF NOT EXISTS trilhas (
                                       id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       titulo    VARCHAR(180) NOT NULL,
    descricao VARCHAR(800),
    ativa     BOOLEAN DEFAULT TRUE
    );

-- MATRÍCULAS
CREATE TABLE IF NOT EXISTS matriculas (
                                          id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          user_id   BIGINT NOT NULL,
                                          trilha_id BIGINT NOT NULL,
                                          criada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          CONSTRAINT uk_matricula UNIQUE (user_id, trilha_id),
    CONSTRAINT fk_m_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_m_trilha FOREIGN KEY (trilha_id) REFERENCES trilhas(id)
    );
